# Copyright (c) 2020, CMCC Technologies Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

open_cli_schema_version: 1.0
name: onap-config
description: |
  Set Onap Common configurations

  example：
  oclip --product onap-dublin onap-config --content "{\"vnf\":{\"vendor\":null,\"name\":null,\"vnf_csar\":null,\"vnfm_driver\":null},\"cloud\":{\"identityUrl\":null,\"username\":null,\"password\":null,\"region\":null,\"version\":null,\"tenant\":null},\"vnfm\":{\"hwvnfmdriver\":{\"name\":null,\"url\":null,\"username\":null,\"password\":null}},\"onap\":null,\"subscription\":null}"

info:
  product: onap-dublin
  service: vnf-validation
  author: ONAP VTP Team

parameters:
  - name: profile-config-path
    description: Configuration file path
    type: string
    short_option: x
    long_option: profile-config-path
    default_value: $s{env:OPEN_CLI_HOME}
    is_optional: true
  - name: content
    description: json string for vim
    type: string
    short_option: A
    long_option: content
    is_optional: false
results:
  direction: portrait
  attributes:
    - name: file_name
      description: test case result
      scope: short
      type: string
cmd:
  command:
    -  python3 $s{env:OPEN_CLI_HOME}/script/onap-config.py --content ${content} --result-json $s{tmp:result.json}  --conf ${profile-config-path}
  success_codes:
    - 0
  working_directory: .
  output: $s{tmp:result.json}
  result_map:
    file_name: $o{$.file_name}

