open_cli_sample_version: 1.0
name: onap-config
version: onap-dublin
samples:
  sample1:
    name: onap-config
    input: --content "{\"vnf\":{\"vendor\":null,\"name\":null,\"vnf_csar\":null,\"vnfm_driver\":null},\"cloud\":{\"identityUrl\":null,\"username\":null,\"password\":null,\"region\":null,\"version\":null,\"tenant\":null},\"vnfm\":{\"hwvnfmdriver\":{\"name\":null,\"url\":null,\"username\":null,\"password\":null}},\"onap\":null,\"subscription\":null}"
    moco: onap-config-dublin-schema-moco.json
    output: |
      +------------+--------------------------------------------+
      |property    |value                                       |
      +------------+--------------------------------------------+
      |file_name   |61520c48-5df4-11ea-8ff6-000c2916b92d.json   |
      +------------+--------------------------------------------+

